### PR TITLE
Update Search Features

### PR DESCRIPTION
**Pull request by eportet**
Changed search names to fit the description of the current Twitter advanced search on the browser.

### CODE REVIEW

**Comment by hemogre** [comment]
Hello,
I read your code but I don't see exactly what it does. Could you provide a bit of documentation on the new possibilities?
Just to give a short sentence on what are the purpose of this:
"query=", 
"exact=", 
"any=", 
"exclude=", 
"hashtag=", 
"author=", 
"recipient=", 
"mention=", 
"lang="

Even if some are obvious, it would be cool to avoid having any confusion
Thanks a lot for this!

**Comment by eportet** [comment]
Hey, I pushed this by accident, that's why I closed it immediately. The point of my changes was to update the code so that it works like the [Twitter Advanced Search](https://twitter.com/search-advanced?lang=en). That way users will be able to match more accurately what they would be able to search on the Twitter search engine. I did this because I wanted to search for hashtags in Tweets. I don't know if the changes that I pushed actually work because they were pushed accidentally, but I  do have a working version now if anyone is interested.

**Comment by eportet** [comment]
So you could specify a search for a tweet from `@michaeljackson` that includes the hashtag `#ABC123` by writing `--author=michaeljackson --hashtag=abc123`

**Comment by hemogre** [comment]
Thanks!

Actually I was looking at this search tool by twitter aaaaaand it's only to construct the QuerySearch.
whatever you're putting in the different fields it's translated in one simple query.

Few examples that gives the same result:
Exact Query : Honda cars
Normal Query : "Honda cars"

Any Query : Honda Toyota
Normal Query : Honda OR Toyota

Exact Query: Honda stadium + Exclude Query : car
Normal Query : "Honda stadium" -car 

You can add AND, OR and maybe some other stuff
So you can do more maybe with the logic operator than twitter allow you to do?

**Pull request closed without merging**
